#include <stdio.h>
#include <stdlib.h>
#include <unistd.h> /* for fork */
#include <sys/types.h> /* for pid_t */
#include <sys/wait.h> /* for wait */

void checkFork(int rc);
void throwError();

/****************************************************************************
* Main process
* Arguements: num args, argv contain [./process, pre char, post char, input]
* Thread Safety: NONE
* Return Values: 0 (success), -1 (fail)
****************************************************************************/
int main (int argc, char *argv[])
{
    int  pidPrefilter = 0;
    int  pidPostfilter = 0;
    char prefilterChar[2] = {0};
    char postfilterChar[2] = {0};
    int  pipe1[2];
    int  pipe2[2];
    char ** command = 0;
    int  status;

    if(argc < 4) {
        fprintf(stderr, "process <x> <y> <command>\n");
        return -1;
    }
    else {
        //char value for filter passed in through cmd line args
        prefilterChar[0] = *argv[1];
        postfilterChar[0] = *argv[2];

        command = malloc(sizeof(char *) * argc - 1);

        // get command and filter chars
        int i;
        for(i = 0; i < argc - 3; i++) {
            command[i] = argv[i+3];
        }
    }

    if(pipe(pipe1) == -1) throwError();
    if(pipe(pipe2) == -1) throwError();

    //command child
    int pidCommand = fork();
    checkFork(pidCommand);
    if (pidCommand == 0) {
        if(dup2(pipe1[1], STDOUT_FILENO) == -1) throwError();
        if(close(pipe1[0]) == -1) throwError();
        printf("its cmd");
        if(execvp(command[0], command) == -1) throwError();
    }
    if(close(pipe1[1])== -1) throwError(6);

    //child for prefilter
    pidPrefilter = fork();
    checkFork(pidPrefilter);
    if(pidPrefilter == 0) {
        if(dup2(pipe1[0], 0) == -1) throwError();
        if(dup2(pipe2[1], 1) == -1) throwError();
        if(close(pipe2[0])== -1) throwError();
        //execute prefilter
        if(execl("./prefilter", "prefilter",  prefilterChar, (char *)0) == -1)
          throwError();
    }
    if(close(pipe2[1]) == -1) throwError();

    //child for postfilter
    pidPostfilter = fork();
    checkFork(pidPostfilter);

    if(pidPostfilter == 0) {
        if(dup2(pipe2[0], 0) == -1) throwError();
        //execute postfilter
        printf("its post");
        if(execl("./postfilter", "postfilter", postfilterChar, (char *)0) == -1)
          throwError();
    }

    // wait as described in man pages
    int i = 0;
    for(i = 0; i< 3; i++) {
        if (wait(&status) == -1) {
            perror("waitpid");
            exit(EXIT_FAILURE);
        }
    }

    //free allocated memory
    free(command);

    return 0;
}

/****************************************************************************
* Checks if a particular fork failed
* Arguements: int value generated upon creating a fork()
* Thread Safety: NONE
****************************************************************************/
void checkFork(int rc) {
    if (rc < 0) {
        fprintf(stderr, "fork failed");
        exit(1);
    }
}

/****************************************************************************
* Throws error generated by system calls
* Arguements: NONE
* Thread Safety: NONE
****************************************************************************/
void throwError() {
    perror("The following error occured");//error
    exit(1);
}
